# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Xing's notes"
email: xing@xingyzt.net
description: >- # this means to ignore newlines until "baseurl:"
  Xing's notes on various astronomy and physics stuff
instagram_username: xingyzt
github_username:  flyorboom

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Build settings
theme: minima

domain: xingyzt.net # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://xingyzt.net  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: / # place folder name if the site is served in a subfolder
